"""Summary report formatter for Salesforce support and customer guidance."""

import json
from typing import Dict, Any


class HealthReportFormatter:
    """Formats audit diagnostics into client-ready Markdown and executive summaries."""

    def format_markdown(self, user_audit: Dict[str, Any], csv_audit: Dict[str, Any], report_audit: Dict[str, Any]) -> str:
        lines = []
        lines.append("# Salesforce Cloud Org Health & Support Diagnostic Report")
        lines.append("Generated by: Salesforce Data Health Toolkit\n")

        lines.append("## Executive Health Summary")
        lines.append(f"- **User Management Health:** {user_audit.get('active_users', 0)} Active Users / {user_audit.get('total_users', 0)} Total Users")
        lines.append(f"- **Data Loader Pass Rate:** {csv_audit.get('pass_rate_percentage', 100.0)}% ({csv_audit.get('valid_rows', 0)} valid / {csv_audit.get('total_rows', 0)} total)")
        lines.append(f"- **Report Query Health Score:** {report_audit.get('overall_health_score', 100)} / 100\n")

        lines.append("## 1. User Management & License Findings")
        if user_audit.get("findings"):
            for f in user_audit["findings"]:
                lines.append(f"- **[{f['severity']}] {f['category']}:** {f['summary']}")
                lines.append(f"  - *Recommended Remediation:* {f['remediation']}")
        else:
            lines.append("- No user management anomalies detected. Clean license hygiene.\n")

        lines.append("\n## 2. Bulk Data Pre-Flight Validation Findings")
        if csv_audit.get("error_rows", 0) > 0:
            lines.append(f"- **Errors Found:** {csv_audit['error_rows']} rows failed pre-flight checks before Data Loader submission.")
            lines.append("- *Sample Errors:*")
            for err in csv_audit.get("row_errors", [])[:5]:
                lines.append(f"  - Row {err['row_number']}: {', '.join(err['errors'])}")
        else:
            lines.append("- All dataset rows passed pre-flight validation. Safe for Bulk API ingestion.\n")

        lines.append("\n## 3. Report & Dashboard Tuning Recommendations")
        if report_audit.get("recommendations"):
            for rec in report_audit["recommendations"]:
                lines.append(f"- {rec}")
        else:
            lines.append("- Reports follow optimal indexing and date scoping best practices.\n")

        return "\n".join(lines)
